import type { AutoReplyRule } from '@/stores/bot'

export const DUMMY_100_RULES: Omit<AutoReplyRule, 'id' | 'createdAt' | 'stats'>[] = [
  // 1-10: Greetings & Salam
  {
    name: 'Salam Halo / Hi',
    enabled: true,
    priority: 1,
    trigger: { type: 'contains', value: 'halo', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Halo! Selamat datang di Customer Service kami. Ada yang bisa kami bantu hari ini? 😊', delay: 1000 },
  },
  {
    name: 'Salam Pagi',
    enabled: true,
    priority: 1,
    trigger: { type: 'contains', value: 'selamat pagi', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Selamat pagi! Semoga harimu menyenangkan. Silakan tanyakan informasi produk atau layanan kami.', delay: 1000 },
  },
  {
    name: 'Salam Siang',
    enabled: true,
    priority: 1,
    trigger: { type: 'contains', value: 'selamat siang', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Selamat siang! CS kami siap melayani pertanyaan seputar order dan informasi produk.', delay: 1000 },
  },
  {
    name: 'Salam Malam',
    enabled: true,
    priority: 1,
    trigger: { type: 'contains', value: 'selamat malam', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Selamat malam! Terima kasih telah menghubungi kami. Pesan kamu akan dibalas secepatnya.', delay: 1000 },
  },
  {
    name: 'Panggilan P',
    enabled: true,
    priority: 1,
    trigger: { type: 'exact', value: 'p', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Iya kak, ada yang bisa kami bantu? Silakan tuliskan pertanyaanmu dengan lengkap ya. 🙏', delay: 1000 },
  },
  {
    name: 'Assalamualaikum',
    enabled: true,
    priority: 1,
    trigger: { type: 'contains', value: 'assalamualaikum', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Waalaikumsalam kak! Selamat datang di layanan pelanggan kami. Ada yang bisa kami bantu?', delay: 1000 },
  },
  {
    name: 'Panggilan Admin / Min',
    enabled: true,
    priority: 1,
    trigger: { type: 'contains', value: 'admin', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Halo kak! Admin toko siap membantu. Silakan sebutkan nama dan keperluan kamu.', delay: 1000 },
  },
  {
    name: 'Permisi',
    enabled: true,
    priority: 1,
    trigger: { type: 'contains', value: 'permisi', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Iya kak, silakan. Ada yang ingin ditanyakan seputar katalog atau cara pemesanan?', delay: 1000 },
  },
  {
    name: 'Ping Test',
    enabled: true,
    priority: 1,
    trigger: { type: 'exact', value: 'ping', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Pong! Bot WhatsApp otomatis aktif 24/7 dan berjalan lancar. 🟢', delay: 500 },
  },
  {
    name: 'Info Bantuan / Help',
    enabled: true,
    priority: 1,
    trigger: { type: 'contains', value: 'help', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Ketik kata kunci:\n- PRICELIST (Katalog Harga)\n- BAYAR (Info Rekening)\n- ONGKIR (Cek Cek Kirim)\n- LOKASI (Alamat Toko)', delay: 1000 },
  },

  // 11-25: Catalog & Pricing
  {
    name: 'Tanya Harga / Berapa',
    enabled: true,
    priority: 2,
    trigger: { type: 'contains', value: 'harga', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Harga produk kami mulai dari Rp 49.000 saja kak! Ketik KATALOG untuk melihat daftar lengkap.', delay: 1000 },
  },
  {
    name: 'Pricelist',
    enabled: true,
    priority: 2,
    trigger: { type: 'contains', value: 'pricelist', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Daftar Harga Resmi:\n1. Paket A: Rp 75.000\n2. Paket B: Rp 150.000\n3. Paket Pro: Rp 299.000', delay: 1000 },
  },
  {
    name: 'Katalog Produk',
    enabled: true,
    priority: 2,
    trigger: { type: 'contains', value: 'katalog', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Silakan cek katalog lengkap kami melalui link website atau pesan paket rekomendasi ini kak!', delay: 1000 },
  },
  {
    name: 'Diskon & Promo',
    enabled: true,
    priority: 2,
    trigger: { type: 'contains', value: 'diskon', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: '🎉 PROMO HARI INI: Diskon 20% untuk pembelian minimal Rp 100.000 dengan kode promo DISKON20!', delay: 1000 },
  },
  {
    name: 'Voucher',
    enabled: true,
    priority: 2,
    trigger: { type: 'contains', value: 'voucher', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Gunakan kode voucher VOUCHERHEMAT saat checkout untuk potongan langsung Rp 15.000!', delay: 1000 },
  },
  {
    name: 'Ready / Stok',
    enabled: true,
    priority: 2,
    trigger: { type: 'contains', value: 'ready', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Semua varian barang yang ada di katalog statusnya READY STOK dan siap dikirim hari ini kak.', delay: 1000 },
  },
  {
    name: 'Keaslian / Ori',
    enabled: true,
    priority: 2,
    trigger: { type: 'contains', value: 'original', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Semua produk kami 100% ORIGINAL & Garansi uang kembali jika terbukti tiruan.', delay: 1000 },
  },
  {
    name: 'Garansi Produk',
    enabled: true,
    priority: 2,
    trigger: { type: 'contains', value: 'garansi', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Setiap pembelian mendapatkan Garansi Resmi 1 Tahun. Klaim garansi sangat mudah cukup kirim foto nota.', delay: 1000 },
  },
  {
    name: 'Best Seller',
    enabled: true,
    priority: 2,
    trigger: { type: 'contains', value: 'best seller', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Produk Paling Laris bulan ini adalah Varian Premium Pack dengan lebih dari 5.000+ ulasan bintang 5! ⭐', delay: 1000 },
  },
  {
    name: 'Cuci Gudang',
    enabled: true,
    priority: 2,
    trigger: { type: 'contains', value: 'cuci gudang', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Dapatkan produk clearance sale harga miring hingga 50% di kategori Cuci Gudang kami!', delay: 1000 },
  },
  {
    name: 'Grosir / Reseller',
    enabled: true,
    priority: 2,
    trigger: { type: 'contains', value: 'grosir', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Pembelian minimal 12 pcs mendapatkan Harga Grosir Khusus Reseller. Hubungi admin untuk pricelist grosir.', delay: 1000 },
  },
  {
    name: 'Dropship',
    enabled: true,
    priority: 2,
    trigger: { type: 'contains', value: 'dropship', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Kami melayani Dropship! Nama pengirim dan nomor toko kamu akan tertera di resi secara rapi.', delay: 1000 },
  },
  {
    name: 'Ukuran / Size',
    enabled: true,
    priority: 2,
    trigger: { type: 'contains', value: 'ukuran', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Panduan Size Chart: S (LD 90), M (LD 96), L (LD 102), XL (LD 110). Silakan ukur sebelum memesan.', delay: 1000 },
  },
  {
    name: 'Varian Warna',
    enabled: true,
    priority: 2,
    trigger: { type: 'contains', value: 'warna', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Pilihan warna tersedia: Black, Navy, Off-White, Army Green, & Cream Beige.', delay: 1000 },
  },
  {
    name: 'Custom Order',
    enabled: true,
    priority: 2,
    trigger: { type: 'contains', value: 'custom', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Bisa custom sablon/logo minimal order 20 pcs. Kirimkan desain kamu ke WhatsApp ini.', delay: 1000 },
  },

  // 26-40: Payment & Banking
  {
    name: 'Info Pembayaran / Bayar',
    enabled: true,
    priority: 3,
    trigger: { type: 'contains', value: 'bayar', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Metode pembayaran tersedia: Bank Transfer (BCA, Mandiri, BRI), QRIS All Payment, & COD.', delay: 1000 },
  },
  {
    name: 'Rekening BCA',
    enabled: true,
    priority: 3,
    trigger: { type: 'contains', value: 'bca', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'BCA: 1234-5678-90 a.n Toko Official Store. Mohon kirimkan bukti transfer setelah membayar.', delay: 1000 },
  },
  {
    name: 'Rekening Mandiri',
    enabled: true,
    priority: 3,
    trigger: { type: 'contains', value: 'mandiri', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Mandiri: 137-00-1234567-8 a.n Toko Official Store.', delay: 1000 },
  },
  {
    name: 'Rekening BRI',
    enabled: true,
    priority: 3,
    trigger: { type: 'contains', value: 'bri', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'BRI: 0123-01-004567-50-8 a.n Toko Official Store.', delay: 1000 },
  },
  {
    name: 'QRIS Payment',
    enabled: true,
    priority: 3,
    trigger: { type: 'contains', value: 'qris', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Pembayaran QRIS dapat di-scan via GoPay, OVO, DANA, ShopeePay, LinkAja, & Mobile Banking apa saja.', delay: 1000 },
  },
  {
    name: 'Bayar COD (Bayar Tempat)',
    enabled: true,
    priority: 3,
    trigger: { type: 'contains', value: 'cod', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Bisa COD! Pembayaran tunai dilakukan ke kurir saat paket sampai di rumah kamu.', delay: 1000 },
  },
  {
    name: 'GoPay',
    enabled: true,
    priority: 3,
    trigger: { type: 'contains', value: 'gopay', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Transfer GoPay ke nomor 0812-3456-7890 a.n Toko Official.', delay: 1000 },
  },
  {
    name: 'OVO',
    enabled: true,
    priority: 3,
    trigger: { type: 'contains', value: 'ovo', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Transfer OVO ke nomor 0812-3456-7890 a.n Toko Official.', delay: 1000 },
  },
  {
    name: 'DANA',
    enabled: true,
    priority: 3,
    trigger: { type: 'contains', value: 'dana', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Transfer DANA ke nomor 0812-3456-7890 a.n Toko Official.', delay: 1000 },
  },
  {
    name: 'ShopeePay',
    enabled: true,
    priority: 3,
    trigger: { type: 'contains', value: 'shopeepay', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Transfer ShopeePay ke nomor 0812-3456-7890 a.n Toko Official.', delay: 1000 },
  },
  {
    name: 'Konfirmasi Transfer',
    enabled: true,
    priority: 3,
    trigger: { type: 'contains', value: 'konfirmasi bayar', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Terima kasih! Bukti bayar kamu sudah diterima dan akan diverifikasi oleh tim keuangan.', delay: 1000 },
  },
  {
    name: 'Kuitansi / Invoice',
    enabled: true,
    priority: 3,
    trigger: { type: 'contains', value: 'invoice', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Invoice cetak dan faktur pajak akan disertakan dalam box kiriman atau dikirimkan via PDF PDF.', delay: 1000 },
  },
  {
    name: 'Cicilan / Paylater',
    enabled: true,
    priority: 3,
    trigger: { type: 'contains', value: 'cicilan', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Pembayaran cicilan 0% tersedia melalui Kredivo, Akulaku, dan Kartu Kredit di checkout toko.', delay: 1000 },
  },
  {
    name: 'Pengembalian Dana / Refund',
    enabled: true,
    priority: 3,
    trigger: { type: 'contains', value: 'refund', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Proses refund dana membutuhkan waktu 1-3 hari kerja ke rekening asal pemesan.', delay: 1000 },
  },
  {
    name: 'Biaya Penanganan',
    enabled: true,
    priority: 3,
    trigger: { type: 'contains', value: 'biaya admin', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Transfer bank tidak dikenakan biaya admin tambahan. Gratis biaya penanganan!', delay: 1000 },
  },

  // 41-55: Shipping & Logistics
  {
    name: 'Tanya Ongkir',
    enabled: true,
    priority: 4,
    trigger: { type: 'contains', value: 'ongkir', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Sebutkan Kota & Kecamatan tujuan kamu kak untuk pengecekan tarif ongkos kirim hemat.', delay: 1000 },
  },
  {
    name: 'Lacak Resi / Tracking',
    enabled: true,
    priority: 4,
    trigger: { type: 'contains', value: 'resi', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Nomor resi otomatis di-update H+1 setelah pengiriman pukul 20.00 WIB.', delay: 1000 },
  },
  {
    name: 'Pengiriman JNE',
    enabled: true,
    priority: 4,
    trigger: { type: 'contains', value: 'jne', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'JNE REG & YES tersedia. Pick up dilakukan setiap sore pukul 16.00 WIB.', delay: 1000 },
  },
  {
    name: 'Pengiriman J&T',
    enabled: true,
    priority: 4,
    trigger: { type: 'contains', value: 'jnt', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Pengiriman via J&T Express dilakukan setiap hari termasuk hari Sabtu dan Minggu!', delay: 1000 },
  },
  {
    name: 'SiCepat',
    enabled: true,
    priority: 4,
    trigger: { type: 'contains', value: 'sicepat', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'SiCepat HALU & REG tersedia untuk pengiriman super cepat.', delay: 1000 },
  },
  {
    name: 'Gojek / Grab (Instan)',
    enabled: true,
    priority: 4,
    trigger: { type: 'contains', value: 'instan', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Pengiriman Sameday / Instant GoSend & GrabExpress maksimal order sebelum jam 14.00 WIB.', delay: 1000 },
  },
  {
    name: 'Pos Indonesia',
    enabled: true,
    priority: 4,
    trigger: { type: 'contains', value: 'pos', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Pengiriman Pos Kilat Khusus melayani seluruh pelosok pelosok Indonesia.', delay: 1000 },
  },
  {
    name: 'Lacak Paket',
    enabled: true,
    priority: 4,
    trigger: { type: 'contains', value: 'lacak', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Silakan masukkan nomor resi kamu untuk melacak lokasi paket secara realtime.', delay: 1000 },
  },
  {
    name: 'Estimasi Sampai',
    enabled: true,
    priority: 4,
    trigger: { type: 'contains', value: 'estimasi', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Estimasi Pengiriman: Jabodetabek (1-2 hari), Luar Kota Jawa (2-3 hari), Luar Jawa (3-5 hari).', delay: 1000 },
  },
  {
    name: 'Kapan Dikirim',
    enabled: true,
    priority: 4,
    trigger: { type: 'contains', value: 'kapan dikirim', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Orderan masuk sebelum jam 15.00 WIB pasti dikirimkan pada HARI YANG SAMA!', delay: 1000 },
  },
  {
    name: 'Bungkus Kado / Gift Wrap',
    enabled: true,
    priority: 4,
    trigger: { type: 'contains', value: 'kado', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Tersedia layanan bungkus kado + kartu ucapan custom hanya tambah Rp 5.000.', delay: 1000 },
  },
  {
    name: 'Bubble Wrap Safety',
    enabled: true,
    priority: 4,
    trigger: { type: 'contains', value: 'bubble wrap', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Setiap paket dilapisi 3 lapis Bubble Wrap tebal dan stiker Fragile GRATIS!', delay: 1000 },
  },
  {
    name: 'Bebas Ongkir',
    enabled: true,
    priority: 4,
    trigger: { type: 'contains', value: 'free ongkir', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Nikmati Promo Bebas Ongkir potongan hingga Rp 20.000 untuk transaksi di atas Rp 150.000.', delay: 1000 },
  },
  {
    name: 'Paket Belum Sampai',
    enabled: true,
    priority: 4,
    trigger: { type: 'contains', value: 'belum sampai', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Mohon maaf atas keterlambatannya kak. Admin akan bantu kejar pihak ekspedisi terkait resi kamu.', delay: 1000 },
  },
  {
    name: 'Kargo Hemat',
    enabled: true,
    priority: 4,
    trigger: { type: 'contains', value: 'kargo', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Untuk berat barang di atas 5 kg kami rekomendasikan pengiriman Kargo (JNE Trucking / J&T Cargo).', delay: 1000 },
  },

  // 56-70: Hours & Location
  {
    name: 'Jam Operasional / Jam Kerja',
    enabled: true,
    priority: 5,
    trigger: { type: 'contains', value: 'jam berapa', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Jam Buka Toko: Senin - Sabtu (08.00 - 20.00 WIB). Hari Minggu & Tanggal Merah Libur.', delay: 1000 },
  },
  {
    name: 'Toko Offline / Alamat',
    enabled: true,
    priority: 5,
    trigger: { type: 'contains', value: 'alamat', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Alamat Toko Offline: Jl. Merdeka Utama No. 88, Jakarta Pusat (Seberang Bank BCA).', delay: 1000 },
  },
  {
    name: 'Google Maps',
    enabled: true,
    priority: 5,
    trigger: { type: 'contains', value: 'maps', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Lokasi Google Maps: Ketik "Toko Official Store Pusat" di aplikasi Google Maps kamu.', delay: 1000 },
  },
  {
    name: 'Hari Libur',
    enabled: true,
    priority: 5,
    trigger: { type: 'contains', value: 'libur', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Toko libur di hari Minggu & Hari Besar Nasional. Chat masuk akan dibalas di hari kerja berikutnya.', delay: 1000 },
  },
  {
    name: 'Cabang Toko',
    enabled: true,
    priority: 5,
    trigger: { type: 'contains', value: 'cabang', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Cabang Resmi: 1. Jakarta Pusat, 2. Surabaya Barat, 3. Bandung Kota.', delay: 1000 },
  },
  {
    name: 'Parkir Toko',
    enabled: true,
    priority: 5,
    trigger: { type: 'contains', value: 'parkir', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Area toko kami memiliki fasilitas parkir mobil & motor yang luas dan gratis.', delay: 1000 },
  },
  {
    name: 'Patokan Lokasi',
    enabled: true,
    priority: 5,
    trigger: { type: 'contains', value: 'patokan', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Patokan: Ruko cat biru di sebelah Minimarket Indomaret pas samping gapura masuk.', delay: 1000 },
  },

  // 71-85: Order & Booking
  {
    name: 'Cara Order',
    enabled: true,
    priority: 6,
    trigger: { type: 'contains', value: 'cara order', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Format Order:\nNama:\nNo HP:\nAlamat Lengkap:\nPesanan & Varian:\nKirimkan format ini ke WhatsApp kami!', delay: 1000 },
  },
  {
    name: 'Reservasi / Booking',
    enabled: true,
    priority: 6,
    trigger: { type: 'contains', value: 'booking', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Untuk booking jadwal konsultasi/service silakan sebutkan Tanggal & Jam kedatangan yang kamu inginkan.', delay: 1000 },
  },
  {
    name: 'Ubah Alamat Order',
    enabled: true,
    priority: 6,
    trigger: { type: 'contains', value: 'ubah alamat', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Pengubahan alamat hanya bisa dilakukan sebelum paket diserahkan ke pihak ekspedisi (sebelum jam 15.00).', delay: 1000 },
  },

  // 86-100: CS & Troubleshooting
  {
    name: 'Komplain Produk',
    enabled: true,
    priority: 7,
    trigger: { type: 'contains', value: 'komplain', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Mohon maaf atas ketidaknyamanannya. Mohon sertakan Video Unboxing tanpa terpotong untuk klaim retur.', delay: 1000 },
  },
  {
    name: 'Barang Rusak',
    enabled: true,
    priority: 7,
    trigger: { type: 'contains', value: 'rusak', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Kami siap mengganti barang rusak 100% GRATIS! Kirimkan video kerusakan beserta resi pengiriman.', delay: 1000 },
  },
  {
    name: 'Salah Kirim Barang',
    enabled: true,
    priority: 7,
    trigger: { type: 'contains', value: 'salah kirim', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Kami mohon maaf atas kekeliruan tim kami. Kirimkan foto barang salah dan admin akan tukar barang baru.', delay: 1000 },
  },
  {
    name: 'Barang Kurang / Incomplete',
    enabled: true,
    priority: 7,
    trigger: { type: 'contains', value: 'kurang', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Kekurangan barang akan kami kirimkan susulan atau dikembalikan dalam bentuk refund dana.', delay: 1000 },
  },
  {
    name: 'Hubungi CS Manusia',
    enabled: true,
    priority: 7,
    trigger: { type: 'contains', value: 'bicara cs', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Pesan kamu telah diteruskan ke Customer Service Manusia. Mohon tunggu sebentar ya kak.', delay: 1000 },
  },
  {
    name: 'Urgent / Darurat',
    enabled: true,
    priority: 7,
    trigger: { type: 'contains', value: 'urgent', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Status URGENT terdeteksi. Tim prioritas kami akan menghubungi kamu dalam waktu kurang dari 5 menit.', delay: 500 },
  },
  {
    name: 'Terima Kasih / Thanks',
    enabled: true,
    priority: 8,
    trigger: { type: 'contains', value: 'terima kasih', caseSensitive: false },
    conditions: { onlyPrivate: false, onlyGroups: false, allowedNumbers: [], blockedNumbers: [] },
    response: { type: 'text', text: 'Sama-sama kak! Senang bisa membantu. Jangan ragu menghubungi kami kembali ya. Stay safe! ✨', delay: 1000 },
  },
]
